<?php /* Smarty version 2.6.18-dev, created on 2011-01-03 14:15:55
         compiled from wiki:Google+Calendar */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'wiki:Google Calendar', 2, false),array('modifier', 'default', 'wiki:Google Calendar', 2, false),)), $this); ?>
This is a Google Calendar.
<iframe src="http://www.google.com/calendar/embed?<?php if ($this->_tpl_vars['type'] == 'title'): ?>title=<?php echo ((is_array($_tmp=$this->_tpl_vars['title'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endif; ?><?php if (is_array ( $this->_tpl_vars['id'] )): ?><?php $_from = $this->_tpl_vars['id']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['i']):
?>src=<?php echo ((is_array($_tmp=$this->_tpl_vars['i'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endforeach; endif; unset($_from); ?><?php else: ?>src=<?php echo ((is_array($_tmp=$this->_tpl_vars['id'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endif; ?><?php if (is_array ( $this->_tpl_vars['color'] )): ?><?php $_from = $this->_tpl_vars['color']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['c']):
?>color=%23<?php echo ((is_array($_tmp=$this->_tpl_vars['c'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endforeach; endif; unset($_from); ?><?php else: ?>color=%23<?php echo ((is_array($_tmp=$this->_tpl_vars['color'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endif; ?>height=<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['height'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')))) ? $this->_run_mod_handler('default', true, $_tmp, 600) : smarty_modifier_default($_tmp, 600)); ?>
&amp;showTitle=<?php if (isset ( $this->_tpl_vars['showtitle'] ) && ! $this->_tpl_vars['showtitle']): ?>0<?php else: ?>1<?php endif; ?>&amp;showNav=<?php if (isset ( $this->_tpl_vars['shownav'] ) && ! $this->_tpl_vars['shownav']): ?>0<?php else: ?>1<?php endif; ?>&amp;showDate=<?php if (isset ( $this->_tpl_vars['showdate'] ) && ! $this->_tpl_vars['showdate']): ?>0<?php else: ?>1<?php endif; ?>&amp;showTabs=<?php if (isset ( $this->_tpl_vars['showtabs'] ) && ! $this->_tpl_vars['showtabs']): ?>0<?php else: ?>1<?php endif; ?>&amp;wkst=<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['weekstart'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')))) ? $this->_run_mod_handler('default', true, $_tmp, 1) : smarty_modifier_default($_tmp, 1)); ?>
&amp;hl=<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['lang'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')))) ? $this->_run_mod_handler('default', true, $_tmp, 'en') : smarty_modifier_default($_tmp, 'en')); ?>
&amp;mode=<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['view'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')))) ? $this->_run_mod_handler('default', true, $_tmp, 'MONTH') : smarty_modifier_default($_tmp, 'MONTH')); ?>
&amp;<?php if (isset ( $this->_tpl_vars['timezone'] )): ?>ctz=<?php echo ((is_array($_tmp=$this->_tpl_vars['timezone'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
&amp;<?php endif; ?><?php if (isset ( $this->_tpl_vars['bgcolor'] )): ?>bgcolor=%23<?php echo ((is_array($_tmp=$this->_tpl_vars['bgcolor'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'urlpathinfo') : smarty_modifier_escape($_tmp, 'urlpathinfo')); ?>
<?php endif; ?>" width="<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['width'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('default', true, $_tmp, '100%') : smarty_modifier_default($_tmp, '100%')); ?>
" height="<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['height'])) ? $this->_run_mod_handler('escape', true, $_tmp, 'html') : smarty_modifier_escape($_tmp, 'html')))) ? $this->_run_mod_handler('default', true, $_tmp, 600) : smarty_modifier_default($_tmp, 600)); ?>
" frameborder="0" scrolling="no"<?php if (isset ( $this->_tpl_vars['border'] )): ?> style="border: solid 1px #777"><?php endif; ?></iframe>