development:
  adapter: postgis
  encoding: unicode
  database: openurban_development
  schema_search_path: "public, postgis"
  postgis_extension: true
  pool: 5
  host: localhost
  username: openurban
  password: dingbat
  su_username: openurban_su
  su_password: dingbat_su
