development:
  adapter: postgis
  encoding: UTF8
  ctype: en_US.UTF-8
  collate: en_US.UTF-8
  database: openurban_development
  schema_search_path: "public, postgis"
  postgis_extension: true
  pool: 5
  host: localhost
  username: openurban
  password: dingbat
  su_username: openurban_su
  su_password: dingbat_su
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5