development:
  database: openurban_development
  adapter: postgis
  host: localhost
  username: cbryan
  password: 86blysT3
  postgis_extension: true

test:
  database: openurban_test
  adapter: postgis
  host: localhost
  username: cbryan
  password: 86blysT3
  postgis_extension: true

production:
  database: openurban_production
  adapter: postgis
  host: localhost
  username: openurban
  password: openurban
  postgis_extension: true